---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oheuzamy/publicrepositories/CyberSecurityApp
    - echo "Starting deployment to $DEPLOYPATH"
    - if [ ! -d "$DEPLOYPATH" ]; then mkdir -p $DEPLOYPATH; fi
    - /bin/cp -r * $DEPLOYPATH
    - echo "Files copied to $DEPLOYPATH"
    - echo "Deployment complete"